# Autogenerated wrapper script for lttng_tools_jll for i686-linux-musl
export liblttng_ctl, lttng, lttng_consumerd, lttng_crash, lttng_relayd, lttng_sessiond

using URCU_jll
using Popt_jll
using XML2_jll
using lttng_ust_jll
JLLWrappers.@generate_wrapper_header("lttng_tools")
JLLWrappers.@declare_library_product(liblttng_ctl, "liblttng-ctl.so.0")
JLLWrappers.@declare_executable_product(lttng)
JLLWrappers.@declare_executable_product(lttng_consumerd)
JLLWrappers.@declare_executable_product(lttng_crash)
JLLWrappers.@declare_executable_product(lttng_relayd)
JLLWrappers.@declare_executable_product(lttng_sessiond)
function __init__()
    JLLWrappers.@generate_init_header(URCU_jll, Popt_jll, XML2_jll, lttng_ust_jll)
    JLLWrappers.@init_library_product(
        liblttng_ctl,
        "lib/liblttng-ctl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lttng,
        "bin/lttng",
    )

    JLLWrappers.@init_executable_product(
        lttng_consumerd,
        "lib/lttng/libexec/lttng-consumerd",
    )

    JLLWrappers.@init_executable_product(
        lttng_crash,
        "bin/lttng-crash",
    )

    JLLWrappers.@init_executable_product(
        lttng_relayd,
        "bin/lttng-relayd",
    )

    JLLWrappers.@init_executable_product(
        lttng_sessiond,
        "bin/lttng-sessiond",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
